import Link from "next/link";
import { notFound } from "next/navigation";
import { updateShipmentStatusAction } from "@/features/incoming/actions/manage-incoming";
import { ShipmentTools } from "@/features/incoming/components/shipment-tools";
import { getIncomingShipment } from "@/features/incoming/data/incoming-repository";
import { formatMoney } from "@/features/sales/money";

export const dynamic = "force-dynamic";
const statuses = ["ordered", "preparing", "shipped", "in_transit", "delivered", "partially_received", "received", "delayed", "issue", "cancelled"];
const label = (status: string) => status.replaceAll("_", " ");

export default async function IncomingShipmentDetail({ params, searchParams }: { params: Promise<{ shipmentId: string }>; searchParams: Promise<{ created?: string }> }) {
  const [{ shipmentId }, query] = await Promise.all([params, searchParams]);
  const data = await getIncomingShipment(shipmentId);
  if (!data) notFound();
  const { shipment, isOwner, packages, receipts } = data;
  const landed = shipment.financials?.landedCents ?? 0;
  const projection = shipment.financials?.projectedRevenueCents ?? null;
  const perPiece = shipment.receivedPieces ? Math.round(landed / shipment.receivedPieces) : 0;
  return <div className="mx-auto max-w-5xl space-y-5">
    <Link href="/incoming" className="inline-flex min-h-11 items-center text-sm font-semibold text-[var(--muted)] hover:text-white">← Back to incoming</Link>
    {query.created === "1" && <p role="status" className="rounded-2xl border border-emerald-400/20 bg-emerald-400/8 px-4 py-3 text-sm text-emerald-200">Shipment created. Add packages as they ship, then record the actual count when it arrives.</p>}
    <section className="surface rounded-[2rem] p-5 sm:p-7"><div className="flex flex-col gap-4 sm:flex-row sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[var(--accent)]">Incoming shipment</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{shipment.name}</h1><p className="mt-2 text-sm text-[var(--muted)]">{shipment.supplierName || "Supplier not recorded"}{shipment.supplierOrderReference ? ` · ${shipment.supplierOrderReference}` : ""}</p></div><div className="rounded-2xl bg-black/20 px-5 py-4"><p className="text-[10px] uppercase text-[var(--muted)]">Actual receiving</p><p className="mt-1 text-xl font-semibold">{shipment.receivedPieces} / {shipment.expectedPieces} pieces</p></div></div>
      <div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-black/20 p-4"><p className="text-[10px] uppercase text-[var(--muted)]">Status</p>{isOwner ? <form action={updateShipmentStatusAction}><input type="hidden" name="shipmentId" value={shipment.id}/><div className="mt-2 flex gap-2"><select name="status" defaultValue={shipment.status} className="min-w-0 flex-1 bg-transparent text-sm font-semibold capitalize outline-none">{statuses.map((status) => <option key={status} value={status}>{label(status)}</option>)}</select><button className="rounded-lg border border-white/10 px-2 py-1 text-xs font-semibold text-[var(--accent)]">Save</button></div></form> : <p className="mt-2 text-sm font-semibold capitalize">{label(shipment.status)}</p>}</div><div className="rounded-2xl bg-black/20 p-4"><p className="text-[10px] uppercase text-[var(--muted)]">Expected delivery</p><p className="mt-2 text-sm font-semibold">{shipment.expectedDeliveryOn || "Not recorded"}</p></div><div className="rounded-2xl bg-black/20 p-4"><p className="text-[10px] uppercase text-[var(--muted)]">Visibility</p><p className="mt-2 text-sm font-semibold">{shipment.visibility === "owner_only" ? "Owner only" : "Shared logistics"}</p></div></div>
      {isOwner && <div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-red-400/15 bg-red-400/5 p-4"><p className="text-[10px] uppercase text-[var(--muted)]">Landed cost 🔒</p><p className="mt-2 text-xl font-semibold">{formatMoney(landed)}</p></div><div className="rounded-2xl border border-[var(--accent)]/15 bg-[var(--accent)]/5 p-4"><p className="text-[10px] uppercase text-[var(--muted)]">Projected revenue 🔒</p><p className="mt-2 text-xl font-semibold">{projection ? formatMoney(projection) : "Not set"}</p></div><div className="rounded-2xl bg-black/20 p-4"><p className="text-[10px] uppercase text-[var(--muted)]">Cost per received piece</p><p className="mt-2 text-xl font-semibold">{shipment.receivedPieces ? formatMoney(perPiece) : "Receive goods first"}</p></div></div>}
    </section>
    {isOwner && shipment.receivedPieces > 0 && <Link href={`/intake?shipment=${shipment.id}${perPiece ? `&unitCost=${(perPiece / 100).toFixed(2)}` : ""}`} className="flex min-h-14 items-center justify-between rounded-2xl bg-[var(--accent)] px-5 text-sm font-bold text-black">Start item intake from this shipment <span>→</span></Link>}
    {isOwner && <ShipmentTools shipmentId={shipment.id} packages={packages}/>}<section className="surface rounded-[2rem] p-5 sm:p-6"><h2 className="font-semibold">Packages</h2>{packages.length ? <div className="mt-4 divide-y divide-white/8">{packages.map((item, index) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><p className="text-sm font-semibold">{item.carrier || `Package ${index + 1}`}{item.tracking_number ? ` · ${item.tracking_number}` : ""}</p><p className="mt-1 text-xs capitalize text-[var(--muted)]">{label(item.status)}{item.last_known_location ? ` · ${item.last_known_location}` : ""}</p></div>{item.tracking_url && <a href={item.tracking_url} target="_blank" rel="noreferrer" className="text-sm font-semibold text-[var(--accent)]">Open tracking ↗</a>}</div>)}</div> : <p className="mt-4 text-sm text-[var(--muted)]">No packages recorded yet.</p>}</section>
    <section className="surface rounded-[2rem] p-5 sm:p-6"><h2 className="font-semibold">Receiving history</h2>{receipts.length ? <div className="mt-4 divide-y divide-white/8">{receipts.map((item) => <div key={item.id} className="flex items-center justify-between gap-3 py-3"><div><p className="text-sm font-semibold">+{item.received_pieces} pieces{item.exception_type ? ` · ${label(item.exception_type)}` : ""}</p><p className="mt-1 text-xs text-[var(--muted)]">{item.notes || new Date(item.received_at).toLocaleDateString()}</p></div></div>)}</div> : <p className="mt-4 text-sm text-[var(--muted)]">Nothing has been received yet.</p>}</section>
  </div>;
}
