"use client";

import { useActionState } from "react";
import { addPackageAction, receiveShipmentAction, type IncomingState } from "@/features/incoming/actions/manage-incoming";

const initial: IncomingState = { status: "idle", message: "" };
const input = "mt-2 min-h-11 w-full rounded-xl border border-white/10 bg-black/25 px-3 text-sm outline-none focus:border-[var(--accent)]";
export function ShipmentTools({ shipmentId, packages }: { shipmentId: string; packages: { id: string; carrier: string | null; tracking_number: string | null }[] }) {
  const [packageState, packageAction, adding] = useActionState(addPackageAction, initial); const [receiptState, receiptAction, receiving] = useActionState(receiveShipmentAction, initial);
  return <div className="grid gap-4 lg:grid-cols-2"><form action={packageAction} className="surface rounded-[2rem] p-5"><input type="hidden" name="shipmentId" value={shipmentId}/><h2 className="font-semibold">Add a package</h2><p className="mt-1 text-xs text-[var(--muted)]">Manual tracking only—no fake carrier events.</p><div className="mt-4 grid gap-3"><input name="carrier" placeholder="Carrier (optional)" className={input}/><input name="tracking" placeholder="Tracking number (optional)" className={input}/><input name="trackingUrl" type="url" placeholder="Tracking link (optional)" className={input}/><select name="status" defaultValue="pending" className={input}><option value="pending">Pending</option><option value="shipped">Shipped</option><option value="in_transit">In transit</option><option value="delivered">Delivered</option><option value="issue">Issue</option></select><input name="expectedPieces" type="number" min="1" step="1" placeholder="Pieces in this package (optional)" className={input}/></div>{packageState.message && <p role="alert" className="mt-3 text-sm text-red-200">{packageState.message}</p>}<button disabled={adding} className="mt-4 min-h-11 w-full rounded-xl border border-white/10 bg-white/8 text-sm font-semibold disabled:opacity-50">{adding ? "Adding…" : "Add package"}</button></form><form action={receiptAction} className="surface rounded-[2rem] p-5"><input type="hidden" name="shipmentId" value={shipmentId}/><h2 className="font-semibold">Receive pieces</h2><p className="mt-1 text-xs text-[var(--muted)]">Delivered means it arrived; receiving is the actual count.</p><div className="mt-4 grid gap-3"><input required name="receivedPieces" type="number" min="1" step="1" placeholder="How many pieces did you receive?" className={input}/><select name="packageId" className={input}><option value="">No package selected</option>{packages.map((item, index) => <option value={item.id} key={item.id}>{item.carrier || "Package"} {item.tracking_number ? `· ${item.tracking_number}` : `#${index + 1}`}</option>)}</select><select name="exceptionType" className={input}><option value="">No exception</option><option value="missing">Missing items</option><option value="extra">Extra items</option><option value="damaged">Damaged</option><option value="wrong_merchandise">Wrong merchandise</option><option value="supplier_error">Supplier error</option><option value="partial_delivery">Partial delivery</option><option value="other">Other</option></select><input name="notes" maxLength={1000} placeholder="Receiving notes (optional)" className={input}/></div>{receiptState.message && <p role="alert" className="mt-3 text-sm text-red-200">{receiptState.message}</p>}<button disabled={receiving} className="mt-4 min-h-11 w-full rounded-xl bg-[var(--accent)] text-sm font-bold text-black disabled:opacity-50">{receiving ? "Saving…" : "Record received pieces"}</button></form></div>;
}
