import Link from "next/link";
import { getSalesOverview } from "@/features/sales/data/sales-repository";
import { formatMoney } from "@/features/sales/money";

export const dynamic = "force-dynamic";
const date = new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric" });
const expenseFields = [["Cost of goods", "cogsCents"], ["Platform fees", "platformFeeCents"], ["Payment fees", "paymentFeeCents"], ["Shipping", "shippingCostCents"], ["Other", "otherCostCents"]] as const;

export default async function SalesPage({ searchParams }: { searchParams: Promise<{ recorded?: string; expenseRecorded?: string; moment?: string; view?: string }> }) {
  const [overview, query] = await Promise.all([getSalesOverview(), searchParams]);
  const ownerView = overview.isOwner && query.view === "owner";
  const totalCosts = overview.sales.reduce((sum, sale) => sum + expenseFields.reduce((costs, [, key]) => costs + (sale[key] ?? 0), 0), 0) + overview.operatingExpenseCents;
  const cards = ownerView
    ? [["Revenue", formatMoney(overview.revenueCents)], ["Total expenses", formatMoney(totalCosts)], ["Net profit", formatMoney(overview.profitCents)], ["Avg. sale", overview.sales.length ? formatMoney(overview.averageSaleCents) : "—"]]
    : [["Sales recorded", String(overview.sales.length)], ["Units available", String(overview.candidates.length)]];

  return <div className="space-y-6">
    <div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[var(--accent)]">Sales</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em]">{ownerView ? "Owner finances." : "Shared sales activity."}</h1><p className="mt-2 text-sm text-[var(--muted)]">{ownerView ? "Private costs, fees, expenses, and realized profit—owner access only." : "The team can record and follow sales without seeing private cost details."}</p></div><Link href="/sales/record" className="grid min-h-12 place-items-center rounded-2xl bg-[var(--accent)] px-6 text-sm font-bold text-black">Record sale</Link></div>
    {overview.isOwner && <div className="inline-flex rounded-2xl border border-white/10 bg-white/[.025] p-1"><Link href="/sales" className={`rounded-xl px-4 py-2.5 text-sm font-semibold ${!ownerView ? "bg-white/10 text-white" : "text-[var(--muted)]"}`}>Team sales</Link><Link href="/sales?view=owner" className={`rounded-xl px-4 py-2.5 text-sm font-semibold ${ownerView ? "bg-[var(--accent)] text-black" : "text-[var(--muted)]"}`}>Owner finances 🔒</Link></div>}
    {query.recorded === "1" && <div role="status" className="rounded-2xl border border-emerald-400/20 bg-emerald-400/8 px-4 py-3 text-sm text-emerald-200">{query.moment === "1" ? "Sale recorded and Sold Moment saved. Inventory and dashboard totals are updated." : "Sale recorded. Inventory and dashboard totals are updated."}</div>}
    {query.expenseRecorded === "1" && <div role="status" className="rounded-2xl border border-emerald-400/20 bg-emerald-400/8 px-4 py-3 text-sm text-emerald-200">Expense recorded. Owner net profit and expense totals are updated.</div>}
    <div className={`grid grid-cols-2 gap-3 ${ownerView ? "lg:grid-cols-4" : "max-w-xl"}`}>{cards.map(([label, value]) => <div key={label} className="surface rounded-3xl p-5"><p className="text-xs text-[var(--muted)]">{label}</p><p className="mt-3 text-2xl font-semibold">{value}</p></div>)}</div>
    {ownerView && <section className="surface rounded-[2rem] p-5 sm:p-6"><h2 className="font-semibold">Expense breakdown</h2><p className="mt-1 text-xs text-[var(--muted)]">Only you can access these numbers.</p><div className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-5">{expenseFields.map(([label, key]) => <div key={key} className="rounded-2xl bg-black/20 p-4"><p className="text-[10px] uppercase tracking-wide text-[var(--muted)]">{label}</p><p className="mt-2 font-semibold">{formatMoney(overview.sales.reduce((sum, sale) => sum + (sale[key] ?? 0), 0))}</p></div>)}</div></section>}
    {ownerView && <section className="surface rounded-[2rem] p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold">Operating expenses</h2><p className="mt-1 text-xs text-[var(--muted)]">Personal draws and historical expenses live here too.</p></div><Link href="/sales/expenses/new" className="grid min-h-11 place-items-center rounded-2xl bg-[var(--accent)] px-5 text-sm font-bold text-black">+ Record expense</Link></div>{overview.expenses.length ? <div className="mt-5 divide-y divide-white/8">{overview.expenses.slice(0, 12).map((expense) => <div key={expense.id} className="flex items-center justify-between gap-4 py-3"><div><p className="text-sm font-semibold">{expense.description}</p><p className="mt-1 text-xs capitalize text-[var(--muted)]">{expense.category.replaceAll("_", " ")} · {expense.occurredOn}</p></div><p className="font-semibold text-red-200">−{formatMoney(expense.amountCents)}</p></div>)}</div> : <p className="mt-5 text-sm text-[var(--muted)]">No standalone expenses recorded yet.</p>}</section>}
    <section className="surface overflow-hidden rounded-[2rem]"><div className="p-5 sm:p-6"><h2 className="font-semibold">{ownerView ? "Private transaction ledger" : "Sales ledger"}</h2><p className="mt-1 text-xs text-[var(--muted)]">{ownerView ? "Sale price, costs, fees, and deterministic realized profit." : "Product, marketplace, date, and sale amount only."}</p></div>
      {!overview.sales.length ? <div className="m-5 mt-0 grid min-h-64 place-items-center rounded-3xl border border-dashed border-white/10 bg-black/10 text-center"><div><div className="mx-auto grid size-12 place-items-center rounded-2xl bg-white/5 text-xl">$</div><p className="mt-4 text-sm font-medium">No transactions recorded</p><p className="mt-1 text-xs text-[var(--muted)]">Your first completed sale starts the ledger.</p></div></div> : <div className="divide-y divide-white/8">{overview.sales.map((sale) => <Link key={sale.id} href={`/inventory/${sale.inventoryUnitId}`} className={`grid gap-3 p-5 transition hover:bg-white/[.025] ${ownerView ? "sm:grid-cols-[minmax(0,1fr)_repeat(3,8rem)]" : "sm:grid-cols-[minmax(0,1fr)_8rem]"} sm:items-center sm:px-6`}><div><p className="font-semibold">{sale.productName}</p><p className="mt-1 text-xs uppercase tracking-wide text-[var(--muted)]">{sale.sku} · {sale.platform} · {date.format(new Date(sale.soldAt))}</p></div><div><p className="text-[10px] uppercase text-[var(--muted)]">Sale amount</p><p className="mt-1 text-sm font-semibold">{formatMoney(sale.salePriceCents)}</p></div>{ownerView && <><div><p className="text-[10px] uppercase text-[var(--muted)]">Total costs</p><p className="mt-1 text-sm font-semibold">{formatMoney(sale.salePriceCents - (sale.profitCents ?? 0))}</p></div><div><p className="text-[10px] uppercase text-[var(--muted)]">Profit</p><p className={`mt-1 text-sm font-bold ${(sale.profitCents ?? 0) >= 0 ? "text-[var(--accent)]" : "text-red-300"}`}>{formatMoney(sale.profitCents ?? 0)}</p></div></>}</Link>)}</div>}
    </section>
  </div>;
}
