"use client";

import { useActionState } from "react";
import { recordExpenseAction, type RecordExpenseState } from "@/features/sales/actions/record-expense";

const initialState: RecordExpenseState = { status: "idle", message: "" };
const inputClass = "mt-2 min-h-12 w-full rounded-2xl border border-white/10 bg-black/25 px-4 text-base text-white outline-none focus:border-[var(--accent)] focus:ring-3 focus:ring-[var(--accent-glow)]";

export function RecordExpenseForm({ today }: { today: string }) {
  const [state, action, pending] = useActionState(recordExpenseAction, initialState);
  return <form action={action} className="surface rounded-[2rem] p-5 sm:p-7"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[var(--accent)]">Owner finances</p><h1 className="mt-2 text-2xl font-semibold tracking-tight sm:text-3xl">Record an expense</h1><p className="mt-2 text-sm leading-6 text-[var(--muted)]">Use this for real business spending or historical adjustments. It changes owner net profit, never past sales.</p><div className="mt-7 grid gap-5 sm:grid-cols-2"><label><span className="text-sm font-medium">Label</span><select name="category" className={inputClass}><option value="supplies">Supplies / packaging</option><option value="travel">Sourcing / travel</option><option value="subscription">Software / subscription</option><option value="shipping">Shipping expense</option><option value="taxes">Taxes</option><option value="personal_draw">Personal / took profit</option><option value="historical_adjustment">Historical expense</option><option value="other">Other</option></select></label><label><span className="text-sm font-medium">Amount</span><div className="relative"><span className="pointer-events-none absolute left-4 top-[1.05rem] text-[var(--muted)]">$</span><input required inputMode="decimal" name="amount" placeholder="0.00" className={`${inputClass} pl-8`}/></div></label><label><span className="text-sm font-medium">Expense date</span><input required type="date" name="occurredOn" defaultValue={today} className={inputClass}/></label><label className="sm:col-span-2"><span className="text-sm font-medium">What was it for?</span><input required maxLength={280} name="description" placeholder="Example: Labels and mailers bought before Reselling OS" className={inputClass}/></label></div>{state.message && <p role="alert" className="mt-5 rounded-2xl border border-red-400/25 bg-red-400/10 px-4 py-3 text-sm text-red-100">{state.message}</p>}<button disabled={pending} className="mt-7 min-h-13 w-full rounded-2xl bg-[var(--accent)] px-6 text-sm font-bold text-black shadow-[0_0_30px_var(--accent-glow)] disabled:opacity-50">{pending ? "Recording expense…" : "Record private expense"}</button></form>;
}
